/*
 * Component registry.
 *
 * One entry per copy-pasteable piece. It drives three things:
 *   1. the browse pages under /components
 *   2. the source code shown on each page, read from disk at build time
 *   3. the shadcn compatible JSON served from /r/<slug>.json
 *
 * Keep `dependencies` accurate. It is what the install command prints, and a
 * missing entry means someone pastes a component that cannot compile.
 */

export type RegistryCategory =
  | "primitive"
  | "block"
  | "motion"
  | "theme";

export type RegistryItem = {
  slug: string;
  name: string;
  category: RegistryCategory;
  /** One line, said plainly. This is the card subtitle and the JSON description. */
  description: string;
  /** Source files, relative to the repository root. First file is the main one. */
  files: string[];
  /** npm packages the file imports, excluding react and next. */
  dependencies?: string[];
  /** Other registry slugs this one imports. */
  registryDependencies?: string[];
  /** Shown under the preview. The rule this component enforces or the trap it avoids. */
  note?: string;
};

export const registry: RegistryItem[] = [
  /* ----------------------------------------------------------------- motion */
  {
    slug: "marquee",
    name: "Marquee",
    category: "motion",
    description: "Seamless infinite strip for logos, tags or capabilities.",
    files: ["src/components/motion/marquee.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    note: "One per page. Under reduced motion it degrades to a scrollable strip rather than freezing content out of reach.",
  },
  {
    slug: "number-ticker",
    name: "Number ticker",
    category: "motion",
    description: "Counts up to a figure when it scrolls into view.",
    files: ["src/components/motion/number-ticker.tsx"],
    dependencies: ["motion"],
    note: "Counting runs on a motion value written straight to the DOM, so it never re-renders React. Only use it on numbers that are real.",
  },
  {
    slug: "spotlight-card",
    name: "Spotlight card",
    category: "motion",
    description: "Border and surface light up under the cursor.",
    files: ["src/components/motion/spotlight-card.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    note: "The highlight is mixed from the theme accent, so it cannot introduce a second brand colour.",
  },
  {
    slug: "tilt-card",
    name: "Tilt card",
    category: "motion",
    description: "Card that tilts towards the pointer in 3D.",
    files: ["src/components/motion/tilt-card.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    note: "Maximum angle is capped low on purpose. Past ten degrees the type edge blurs.",
  },
  {
    slug: "text-reveal",
    name: "Text reveal",
    category: "motion",
    description: "Word by word entrance for a single statement.",
    files: ["src/components/motion/text-reveal.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    note: "One line per page. The whole sentence stays in the DOM, so it is selectable and announced normally.",
  },
  {
    slug: "aurora-background",
    name: "Aurora background",
    category: "motion",
    description: "Slow moving light behind a section, built from theme tokens.",
    files: ["src/components/motion/aurora-background.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    note: "Uses the theme accent only, which is what stops it becoming the purple mesh every AI site ships.",
  },

  /* ------------------------------------------------------------- primitives */
  {
    slug: "button",
    name: "Button",
    category: "primitive",
    description: "Six variants, three sizes, loading and disabled states.",
    files: ["src/components/primitives/button.tsx"],
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    note: "Labels are whitespace-nowrap, so a two line CTA cannot happen. Accent backgrounds always pair with accent foreground.",
  },
  {
    slug: "form",
    name: "Form controls",
    category: "primitive",
    description: "Field, input, textarea, select, checkbox, radio and switch.",
    files: ["src/components/primitives/form.tsx"],
    dependencies: [
      "@radix-ui/react-select",
      "@radix-ui/react-checkbox",
      "@radix-ui/react-radio-group",
      "@radix-ui/react-switch",
      "@phosphor-icons/react",
      "clsx",
      "tailwind-merge",
    ],
    note: "Field generates the id and aria-describedby and the control reads them from context, so a label without a for cannot ship.",
  },
  {
    slug: "overlay",
    name: "Dialogs and menus",
    category: "primitive",
    description: "Dialog, tooltip, dropdown, popover and context menu.",
    files: ["src/components/primitives/overlay.tsx"],
    dependencies: [
      "@radix-ui/react-dialog",
      "@radix-ui/react-tooltip",
      "@radix-ui/react-dropdown-menu",
      "@radix-ui/react-popover",
      "@radix-ui/react-context-menu",
      "@phosphor-icons/react",
      "clsx",
      "tailwind-merge",
    ],
    note: "Each overlay matches its job: dialog for decisions, popover for supporting controls and context menu for pointer or long-press actions.",
  },
  {
    slug: "feedback",
    name: "Feedback states",
    category: "primitive",
    description: "Alert, skeletons, empty state, error state and progress.",
    files: ["src/components/primitives/feedback.tsx"],
    dependencies: ["@phosphor-icons/react", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
    note: "Skeletons are shaped like the content they replace. There is no page level spinner in the kit.",
  },
  {
    slug: "toast",
    name: "Toast",
    category: "primitive",
    description: "Transient confirmations with a provider and a hook.",
    files: ["src/components/primitives/toast.tsx"],
    dependencies: ["motion", "@phosphor-icons/react", "clsx", "tailwind-merge"],
    note: "Announced politely, never as an alert. Anything the user must act on belongs inline instead.",
  },
  {
    slug: "data",
    name: "Data display",
    category: "primitive",
    description: "Table, stat, avatar, tag, breadcrumb and pagination.",
    files: ["src/components/primitives/data.tsx"],
    dependencies: ["@radix-ui/react-avatar", "@phosphor-icons/react", "clsx", "tailwind-merge"],
    note: "Stat requires a source prop, so a figure with no provenance cannot be rendered.",
  },
  {
    slug: "controls",
    name: "Slider and segmented control",
    category: "primitive",
    description: "Range slider and a two to four option segmented control.",
    files: ["src/components/primitives/controls.tsx"],
    dependencies: ["@radix-ui/react-slider", "@radix-ui/react-toggle-group", "clsx", "tailwind-merge"],
  },
  {
    slug: "accordion",
    name: "Accordion",
    category: "primitive",
    description: "Radix accordion for panels that contain components.",
    files: ["src/components/primitives/accordion.tsx"],
    dependencies: ["@radix-ui/react-accordion", "@phosphor-icons/react", "clsx", "tailwind-merge"],
    note: "For plain question and answer lists use the FAQ block instead, which needs no JavaScript.",
  },
  {
    slug: "tabs",
    name: "Tabs",
    category: "primitive",
    description: "Underline tabs with roving focus.",
    files: ["src/components/primitives/tabs.tsx"],
    dependencies: ["@radix-ui/react-tabs", "clsx", "tailwind-merge"],
  },
  {
    slug: "command-palette",
    name: "Command palette",
    category: "primitive",
    description: "Keyboard-opened search across grouped pages and actions.",
    files: ["src/components/primitives/command-palette.tsx"],
    dependencies: ["@radix-ui/react-dialog", "@phosphor-icons/react", "clsx", "tailwind-merge"],
    note: "Every result must remain reachable through ordinary navigation; the palette is an accelerator, not a hidden sitemap.",
  },
  {
    slug: "advanced-form",
    name: "Advanced form fields",
    category: "primitive",
    description: "Native date, time, one-time-code and file upload fields.",
    files: ["src/components/primitives/advanced-form.tsx"],
    dependencies: ["@phosphor-icons/react", "clsx", "tailwind-merge"],
    note: "Native browser semantics are preserved instead of rebuilding calendars, time pickers and file selection in JavaScript.",
  },
  {
    slug: "combobox",
    name: "Combobox",
    category: "primitive",
    description: "Searchable option picker with keyboard navigation and an empty state.",
    files: ["src/components/primitives/combobox.tsx"],
    dependencies: [
      "@radix-ui/react-popover",
      "@phosphor-icons/react",
      "clsx",
      "tailwind-merge",
    ],
    note: "Use when a select has enough options to justify search. Arrow keys move through results and Enter confirms the active option.",
  },
  {
    slug: "locale-selectors",
    name: "Language and currency selectors",
    category: "primitive",
    description: "Explicit locale controls built on the accessible select primitive.",
    files: ["src/components/primitives/locale-selectors.tsx"],
    // Radix Select and Phosphor arrive through the form dependency; this file
    // only imports form and the cn helper directly.
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["form"],
    note: "Keep language and currency independent: changing the interface language must not silently change prices or checkout currency.",
  },
  {
    slug: "search-results",
    name: "Search result states",
    category: "primitive",
    description: "Results, no-results guidance and recent-search links.",
    files: ["src/components/primitives/search-results.tsx"],
    dependencies: ["@phosphor-icons/react", "clsx", "tailwind-merge"],
    note: "Result counts, query context and a recovery path remain visible. Recent searches are ordinary links and require no client state.",
  },

  /* ----------------------------------------------------------------- blocks */
  {
    slug: "hero-split",
    name: "Split hero",
    category: "block",
    description: "Asymmetric hero, copy left, asset right.",
    files: ["src/components/blocks/hero-split.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
    note: "Subtext is capped at twenty words by the house rules, and the display size is tuned so a forty character headline stays on two lines.",
  },
  {
    slug: "hero-editorial",
    name: "Editorial hero",
    category: "block",
    description: "Statement hero with a full bleed image below the fold line.",
    files: ["src/components/blocks/hero-editorial.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
  },
  {
    slug: "feature-bento",
    name: "Feature bento",
    category: "block",
    description: "Mixed span grid with exact cell count.",
    files: ["src/components/blocks/feature-bento.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    note: "Renders exactly the cells you pass, so an empty tile is impossible.",
  },
  {
    slug: "pricing-duo",
    name: "Pricing duo",
    category: "block",
    description: "Two plans, five features each, one featured.",
    files: ["src/components/blocks/pricing-duo.tsx"],
    dependencies: ["@phosphor-icons/react", "motion", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
  },
  {
    slug: "contact-form",
    name: "Contact form",
    category: "block",
    description: "Labelled fields, inline errors, sending and success states.",
    files: ["src/components/blocks/contact-form.tsx"],
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: ["button", "form"],
  },
  {
    slug: "site-nav",
    name: "Site navigation",
    category: "block",
    description: "Sticky header on one line with a mobile drawer.",
    files: ["src/components/blocks/site-nav.tsx", "src/components/blocks/mobile-nav.tsx"],
    dependencies: ["@radix-ui/react-dialog", "@phosphor-icons/react", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
  },
  {
    slug: "announcement-bar",
    name: "Announcement bar",
    category: "block",
    description: "Dismissible one-line notice above the site navigation.",
    files: ["src/components/blocks/announcement-bar.tsx"],
    dependencies: ["@phosphor-icons/react"],
    note: "Dismissal lasts for the session only. If the message needs two lines, it belongs in a section.",
  },
  {
    slug: "page-header",
    name: "Page header",
    category: "block",
    description: "Breadcrumb, title and introduction for inner pages.",
    files: ["src/components/blocks/page-header.tsx"],
    registryDependencies: ["data"],
    note: "Inner pages need orientation rather than another marketing hero.",
  },
  {
    slug: "logo-wall",
    name: "Logo wall",
    category: "block",
    description: "Quiet social-proof strip for customer or partner marks.",
    files: ["src/components/blocks/logo-wall.tsx"],
    note: "Logos only: no category labels, inflated counts or adjectives.",
  },
  {
    slug: "features-split",
    name: "Split features",
    category: "block",
    description: "Alternating image-and-copy rows, capped at two.",
    files: ["src/components/blocks/features-split.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    note: "A third zigzag row is a signal to switch to a bento, tabs or a separate page.",
  },
  {
    slug: "steps-flow",
    name: "Steps flow",
    category: "block",
    description: "Three or four connected actions without numbered badges.",
    files: ["src/components/blocks/steps-flow.tsx"],
    dependencies: ["motion"],
    note: "Step names describe the action. The reading order carries the sequence.",
  },
  {
    slug: "spec-grouped",
    name: "Grouped specifications",
    category: "block",
    description: "Practical details arranged in three breathable clusters.",
    files: ["src/components/blocks/spec-grouped.tsx"],
    dependencies: ["motion"],
    note: "Each cluster is capped at four rows. Longer specifications belong on a detail page.",
  },
  {
    slug: "gallery-strip",
    name: "Gallery strip",
    category: "block",
    description: "Three-image atmosphere break with optional full bleed.",
    files: ["src/components/blocks/gallery-strip.tsx"],
    dependencies: ["motion", "clsx", "tailwind-merge"],
    note: "Captions sit under images, never as labels over the photography.",
  },
  {
    slug: "stats-band",
    name: "Stats band",
    category: "block",
    description: "Three sourced figures with a section introduction.",
    files: ["src/components/blocks/stats-band.tsx"],
    dependencies: ["motion"],
    registryDependencies: ["data"],
    note: "Every number requires a source, so invented proof has nowhere to hide.",
  },
  {
    slug: "timeline",
    name: "Timeline",
    category: "block",
    description: "Vertical history using real period labels.",
    files: ["src/components/blocks/timeline.tsx"],
    dependencies: ["motion"],
    note: "Use dates or seasons people recognize, not decorative phase numbers.",
  },
  {
    slug: "team-grid",
    name: "Team grid",
    category: "block",
    description: "Portrait-led people grid with name and role.",
    files: ["src/components/blocks/team-grid.tsx"],
    dependencies: ["motion"],
    note: "Biographies belong on person pages rather than beneath a wall of portraits.",
  },
  {
    slug: "blog-grid",
    name: "Blog grid",
    category: "block",
    description: "Editorial cards with category, date and reading time.",
    files: ["src/components/blocks/blog-grid.tsx"],
    dependencies: ["motion"],
    note: "Metadata stays plain and readable instead of floating over the cover image.",
  },
  {
    slug: "proof-quote",
    name: "Proof quote",
    category: "block",
    description: "Single attributed quote with an optional portrait.",
    files: ["src/components/blocks/proof-quote.tsx"],
    dependencies: ["motion"],
    note: "One short quote per section. Longer stories are case studies.",
  },
  {
    slug: "faq-accordion",
    name: "FAQ accordion",
    category: "block",
    description: "Native details-based questions that work without JavaScript.",
    files: ["src/components/blocks/faq-accordion.tsx"],
    dependencies: ["@phosphor-icons/react"],
    note: "Native details keeps the answers keyboard-operable and searchable even while closed.",
  },
  {
    slug: "newsletter-signup",
    name: "Newsletter signup",
    category: "block",
    description: "Single-field signup with validation and success states.",
    files: ["src/components/blocks/newsletter-signup.tsx"],
    registryDependencies: ["button", "form"],
    note: "Errors stay beside the field. A subscription failure is never hidden in a toast.",
  },
  {
    slug: "cta-band",
    name: "CTA band",
    category: "block",
    description: "Closing action with one repeated page intent.",
    files: ["src/components/blocks/cta-band.tsx"],
    dependencies: ["motion"],
    registryDependencies: ["button"],
    note: "Reuse the hero CTA wording so the page closes with the same promise it opened with.",
  },
  {
    slug: "site-footer",
    name: "Site footer",
    category: "block",
    description: "Brand summary with three compact link groups.",
    files: ["src/components/blocks/site-footer.tsx"],
    note: "The footer closes navigation; it does not become a second sitemap.",
  },
  {
    slug: "hero-centered",
    name: "Centered hero",
    category: "block",
    description: "Centered launch statement with two actions and a proof line.",
    files: ["src/components/blocks/hero-centered.tsx"],
    dependencies: ["motion"],
    registryDependencies: ["button"],
    note: "Use when the product has one clear promise and does not need an image to explain itself.",
  },
  {
    slug: "testimonial-grid",
    name: "Testimonial grid",
    category: "block",
    description: "Three equally weighted quotes with full attribution.",
    files: ["src/components/blocks/testimonial-grid.tsx"],
    dependencies: ["motion"],
    note: "Longer stories belong in case studies; this block is for short corroborating evidence.",
  },
  {
    slug: "integration-grid",
    name: "Integration grid",
    category: "block",
    description: "Directory of six to twelve product connections.",
    files: ["src/components/blocks/integration-grid.tsx"],
    dependencies: ["@phosphor-icons/react", "motion"],
    note: "Every card remains readable without a vendor mark because name and description are required.",
  },
  {
    slug: "comparison-table",
    name: "Plan comparison",
    category: "block",
    description: "Feature-level comparison for two or three plans.",
    files: ["src/components/blocks/comparison-table.tsx"],
    dependencies: ["@phosphor-icons/react"],
    registryDependencies: ["button"],
    note: "Use after simple pricing cards when buyers need limits and qualifiers, not more marketing copy.",
  },
  {
    slug: "floating-nav",
    name: "Floating navigation",
    category: "block",
    description: "Rounded floating header for focused launch pages.",
    files: ["src/components/blocks/floating-nav.tsx", "src/components/blocks/mobile-nav.tsx"],
    dependencies: ["@radix-ui/react-dialog", "@phosphor-icons/react", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
    note: "Use when the page background should remain visible around the header.",
  },
  {
    slug: "mega-nav",
    name: "Mega navigation",
    category: "block",
    description: "Multi-column discovery menu for products, services and resources.",
    files: ["src/components/blocks/mega-nav.tsx"],
    dependencies: ["@phosphor-icons/react", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
    note: "Use for four or more primary destinations. Native details keeps grouped links usable without navigation JavaScript.",
  },
  {
    slug: "app-showcase-hero",
    name: "App showcase hero",
    category: "block",
    description: "Product promise followed by a framed interface screenshot.",
    files: ["src/components/blocks/app-showcase-hero.tsx"],
    dependencies: ["motion"],
    registryDependencies: ["button"],
    note: "The screenshot is real product evidence, not a canvas for floating labels and invented charts.",
  },
  {
    slug: "case-study-grid",
    name: "Case study grid",
    category: "block",
    description: "Outcome-led project cards for studios and service businesses.",
    files: ["src/components/blocks/case-study-grid.tsx"],
    dependencies: ["@phosphor-icons/react", "motion"],
    note: "Each card leads with the result; the full process belongs on the linked case-study page.",
  },
  {
    slug: "product-grid",
    name: "Product grid",
    category: "block",
    description: "Two or four-column product collection with price and note.",
    files: ["src/components/blocks/product-grid.tsx"],
    note: "Product imagery carries the hierarchy. Badges and quick-add controls stay opt-in.",
  },
  {
    slug: "dashboard-shell",
    name: "Dashboard shell",
    category: "block",
    description: "Responsive application frame with navigation, title and utility slot.",
    files: ["src/components/blocks/dashboard-shell.tsx"],
    dependencies: ["clsx", "tailwind-merge"],
    note: "The mobile navigation becomes a horizontal strip instead of hiding core destinations.",
  },
  {
    slug: "filter-toolbar",
    name: "Filter toolbar",
    category: "block",
    description: "Search and up to three native filters in a GET form.",
    files: ["src/components/blocks/filter-toolbar.tsx"],
    dependencies: ["@phosphor-icons/react"],
    note: "Native form submission keeps filters shareable in the URL and useful without client state.",
  },
  {
    slug: "metrics-overview",
    name: "Metrics overview",
    category: "block",
    description: "Four compact dashboard metrics with optional change context.",
    files: ["src/components/blocks/metrics-overview.tsx"],
    dependencies: ["@phosphor-icons/react"],
    note: "A change percentage is only shown when its comparison period is meaningful.",
  },
  {
    slug: "auth-split",
    name: "Split authentication",
    category: "block",
    description: "Authentication frame with a form slot and optional product proof.",
    files: ["src/components/blocks/auth-split.tsx"],
    note: "The form remains the primary surface; the second panel disappears on small screens.",
  },
  {
    slug: "docs-sidebar",
    name: "Documentation sidebar",
    category: "block",
    description: "Grouped documentation navigation beside an article slot.",
    files: ["src/components/blocks/docs-sidebar.tsx"],
    note: "On mobile the same links live in native details, so no navigation drawer JavaScript is required.",
  },
  {
    slug: "event-schedule",
    name: "Event schedule",
    category: "block",
    description: "Two-day schedule with time, session, speaker and track.",
    files: ["src/components/blocks/event-schedule.tsx"],
    note: "Times are real text and remain searchable, selectable and readable without a calendar widget.",
  },
  {
    slug: "location-grid",
    name: "Location grid",
    category: "block",
    description: "Address cards for multi-location services and stores.",
    files: ["src/components/blocks/location-grid.tsx"],
    dependencies: ["@phosphor-icons/react"],
    note: "Addresses use semantic address elements and each location may link to its own detail page.",
  },
  {
    slug: "changelog-list",
    name: "Changelog list",
    category: "block",
    description: "Product updates arranged by date, version and concrete changes.",
    files: ["src/components/blocks/changelog-list.tsx"],
    note: "Dates and version labels carry the sequence; decorative timeline markers are unnecessary.",
  },

  /* --------------------------------------------------------------- commerce */
  {
    slug: "product-detail",
    name: "Product detail",
    category: "block",
    description: "Gallery, variant selection, quantity and add-to-cart with real states.",
    files: ["src/components/blocks/product-detail.tsx"],
    dependencies: ["@phosphor-icons/react", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
    note: "Sold-out variants stay visible but disabled, and the add button shows a transient added state. It owns no cart; onAdd hands the choice to the target project.",
  },
  {
    slug: "cart-drawer",
    name: "Cart drawer",
    category: "block",
    description: "Slide-over cart with line items, quantity, subtotal and an empty state.",
    files: ["src/components/blocks/cart-drawer.tsx"],
    dependencies: ["@radix-ui/react-dialog", "@phosphor-icons/react", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
    note: "Radix Dialog handles focus, escape and scroll lock. Presentational: the parent owns the cart data and callbacks.",
  },
  {
    slug: "checkout-form",
    name: "Checkout form",
    category: "block",
    description: "Contact and delivery fields with an order summary and complete states.",
    files: ["src/components/blocks/checkout-form.tsx"],
    dependencies: ["@phosphor-icons/react"],
    registryDependencies: ["button", "form", "feedback"],
    note: "Collects contact and shipping only. Card details go to a payment provider on submit, never on this page.",
  },
  {
    slug: "order-confirmation",
    name: "Order confirmation",
    category: "block",
    description: "Success state with order number, itemised total and a next step.",
    files: ["src/components/blocks/order-confirmation.tsx"],
    dependencies: ["@phosphor-icons/react"],
    registryDependencies: ["button"],
    note: "The success end of the flow. No invented tracking numbers; delivery is an estimate rendered in the page locale.",
  },

  /* ------------------------------------------------------------------ theme */
  {
    slug: "tokens",
    name: "Token contract",
    category: "theme",
    description: "The variables every component in the kit reads.",
    files: ["src/design/tokens.css"],
    note: "Start here. Nothing else works without it, and a hardcoded colour anywhere else is a bug.",
  },
  {
    slug: "themes",
    name: "Sector themes",
    category: "theme",
    description: "Twelve full token sets, one per sector.",
    files: ["src/design/themes.css"],
    registryDependencies: ["tokens"],
    note: "Every pair is checked by npm run audit:contrast, which fails the command below WCAG AA.",
  },
  {
    slug: "theme-runtime",
    name: "Runtime theme switching",
    category: "theme",
    description: "Provider, no-flash script and picker for visitor chosen themes.",
    files: ["src/components/primitives/theme-runtime.tsx"],
    dependencies: ["clsx", "tailwind-merge"],
    note: "Writes to documentElement, so portals inherit the theme. ThemeScope cannot do that.",
  },
];

export const categories: { id: RegistryCategory; label: string; blurb: string }[] = [
  {
    id: "theme",
    label: "Theme",
    blurb: "The token contract and the twelve sector palettes everything else reads.",
  },
  {
    id: "primitive",
    label: "Primitives",
    blurb: "Buttons, forms, overlays, feedback and data display.",
  },
  {
    id: "block",
    label: "Blocks",
    blurb: "Whole page sections that take content as props.",
  },
  {
    id: "motion",
    label: "Motion",
    blurb: "Animated pieces. Each one degrades to something usable under reduced motion.",
  },
];

export const itemBySlug = (slug: string) => registry.find((item) => item.slug === slug);
